# Generated by Django 4.2.11 on 2024-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='profession',
            field=models.TextField(choices=[('actor', 'Actor'), ('creator', 'Creator')], null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(null=True, verbose_name='role'),
        ),
    ]
